### ISSUE TITLE
"Email receipt for a Contribution in a Recurring Series" = "Never" is not working

### ISSUE THREAD

**Issue by cmmadmin** [iATSPayments/com.iatspayments.civicrm#260]
Since our recent upgrade to CiviCRM 5.3.1 and iATS Payments 1.6.2 we have noticed that some of our donors are receiving receipt emails every time a recurring contribution is processed. 

We want donors to only receive an email receipt once when they first sign up for the recurring contribution. This is how it was working before the upgrade.

In CiviCRM, when we Edit a recurring contribution we see an option called "Email receipt for each Contribution in this Recurring Series". When we set this to "No", the email receipts seem to stop.

However, whenever a *new* recurring contribution is created is option is set to "Yes" by default.

In Administer > CiviContribute > iATS Payments Settings > "Email receipt for a Contribution in a Recurring Series" is set to: "Never".

It seems like this setting should fix the issue, but it doesn't seem to be working.

It seems "Email receipt for a Contribution in a Recurring Series" = "Never" is not working.

**Comment by adixon** [comment]
Thanks for your note. I haven't heard of anyone else with this issue, but it doesn't surprise me - we've had this issue frequently enough before!

**Comment by adixon** [comment]
Just another note after re-reading your issue - the "Never" setting does not alter the individual schedule settings, though I suppose it could .. it's supposed to instead prevent civicrm core from using that setting to trigger an email receipt by passing "is_email_receipt = 0" parameter to the completetransaction api call.

**Comment by KarinG** [comment]
I just had a stab at reproducing this on our iATS demo site - and

1) I was able to reproduce this for migrated series (series that already existed prior to in this case 5.3.1)
2) I was not able to reproduce this for newly created in 5.3.1 - they do as told by the iATS Settings: I'm able to swap between Never and as set for a Specific Contribution Series and all is as it should.

It makes no sense to me how for older series the Never setting is ignored, but for newly created series all appears well;

If you want Never your best strategy is:
update civicrm_contribution_recur set is_email_receipt=0;
and have you iATS Settings set at Never

**Comment by adixon** [comment]
It appears that the issue arises with ACH transactions. There was a bug in the verification script (the code that completes transactions that have gone through). 

Fixed with 32fa2e3e01711354307cd097c5a9d5111b17e90d

Let me know if that seems right (i.e. that the issue is only arising for ACH) and if the patch resolves the issue for you.

**Comment by cmmadmin** [comment]
Has this fix been delivered with a new version of the CiviCRM or the payment processor? We are still seeing this issue but have not applied with fix you mentioned since we were uncertain how well test it is.
